name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven  # Caches dependencies for faster builds

    - name: Build JAR using Maven
      run: mvn clean package -DskipTests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/postgresql-replica-api:latest

  deploy:
    needs: build
    runs-on: self-hosted  # Runs on the self-hosted runner in your VM

    steps:
    - name: Pull and restart Docker container
      run: |
        docker pull ghcr.io/${{ github.repository }}/postgresql-replica-api:latest
        docker stop postgresql-replica-api || true
        docker rm postgresql-replica-api || true
        docker run -d --name postgresql-replica-api -p 8080:8080 ghcr.io/${{ github.repository }}/postgresql-replica-api:latest
