name: Deploy Code

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Runs on the self-hosted runner in your VM

    steps:
    - name: Pull and restart Docker container
      run: |
        sudo docker pull ghcr.io/${{ github.repository }}/postgresql-replica-api:latest
        sudo docker stop postgresql-replica-api || true
        sudo docker rm postgresql-replica-api || true
        sudo docker run -d -v /home/ec2-user/run_command.sh:/app/run_command.sh --name postgresql-replica-api -p 8080:8080 ghcr.io/${{ github.repository }}/postgresql-replica-api:latest

    - name: Pull Github Code to pull in terraform files
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: main


    - name: Run Terraform Init
      run: |
        cd tf-resources/terraform
        terraform init
        terraform plan
