name: Deploy Spring Boot App on Self-Hosted VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Explicitly set JAVA_HOME for Maven and Java
        run: |
          export JAVA_HOME=/home/admin/actions-runner/_work/_tool/Java_Temurin-Hotspot_jdk/17.0.14-7/x64
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Build Spring Boot JAR
        run: |
          chmod +x mvnw  # Ensure Maven Wrapper is executable
          ./mvnw clean package -DskipTests
          ls -lah target/

      - name: Copy JAR to Deployment Directory
        run: |
          # Create the deployment directory if it doesn't exist
          sudo mkdir -p /opt/springboot-app
          # Copy the built JAR to the deployment directory (rename if needed)
          sudo cp target/*.jar /opt/springboot-app/your-app.jar

      - name: Configure systemd Service (if not already configured)
        run: |
          sudo bash -c 'cat > /etc/systemd/system/springboot-app.service <<EOF
          [Unit]
          Description=Spring Boot Application
          After=network.target

          [Service]
          User=admin
          ExecStart= /home/admin/actions-runner/_work/_tool/Java_Temurin-Hotspot_jdk/17.0.14-7/x64/bin/java -jar /opt/springboot-app/your-app.jar -jar /opt/springboot-app/your-app.jar
          SuccessExitStatus=143
          Restart=on-failure
          RestartSec=30

          [Install]
          WantedBy=multi-user.target
          EOF'
          sudo systemctl daemon-reload
          sudo systemctl enable springboot-app

      - name: Deploy and Restart Application via systemd
        run: |
          sudo systemctl restart springboot-app

      - name: Verify Application is Running
        run: |
          sleep 30  # Wait a bit for the app to start
          curl -I http://localhost:8080/hello || (echo "App is not running!" && exit 1)
